<script lang="ts">
	let title = '';
	let description = '';
	let methodology = '';
	let dataSources: string[] = [];
	let newSource = '';

	function addDataSource() {
		if (newSource.trim() && !dataSources.includes(newSource.trim())) {
			dataSources = [...dataSources, newSource.trim()];
			newSource = '';
		}
	}

	function removeDataSource(index: number) {
		dataSources = dataSources.filter((_, i) => i !== index);
	}

	function handleExport(format: 'markdown' | 'json' | 'bibtex') {
		let content = '';
		let filename = '';
		let mimeType = '';

		switch (format) {
			case 'markdown':
				content = generateMarkdown();
				filename = 'analysis-description.md';
				mimeType = 'text/markdown';
				break;
			case 'json':
				content = JSON.stringify(
					{
						title,
						description,
						methodology,
						dataSources,
						createdAt: new Date().toISOString()
					},
					null,
					2
				);
				filename = 'analysis-metadata.json';
				mimeType = 'application/json';
				break;
			case 'bibtex':
				content = generateBibtex();
				filename = 'analysis-citation.bib';
				mimeType = 'text/plain';
				break;
		}

		const blob = new Blob([content], { type: mimeType });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = filename;
		a.click();
		URL.revokeObjectURL(url);
	}

	function generateMarkdown(): string {
		return `# ${title}

## Description

${description}

## Methodology

${methodology}

## Data Sources

${dataSources.map((s) => `- ${s}`).join('\n')}

---

*Generated by ODDOL - Open Data Driven Online Learning*
*Date: ${new Date().toLocaleDateString()}*
`;
	}

	function generateBibtex(): string {
		const key = title.toLowerCase().replace(/\s+/g, '_').slice(0, 20);
		return `@misc{${key},
  title = {${title}},
  note = {${description.slice(0, 200)}...},
  howpublished = {ODDOL - Open Data Driven Online Learning},
  year = {${new Date().getFullYear()}}
}`;
	}
</script>

<svelte:head>
	<title>Describe Analysis - ODDOL</title>
</svelte:head>

<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
	<div class="mb-8">
		<h1 class="text-3xl font-bold text-gray-900 mb-2">Describe Your Analysis</h1>
		<p class="text-gray-600">
			Document your data analysis with proper provenance tracking. Export in multiple formats.
		</p>
	</div>

	<div class="space-y-6">
		<!-- Title -->
		<div class="card p-6">
			<label for="title" class="block text-sm font-medium text-gray-700 mb-2">
				Title
			</label>
			<input
				type="text"
				id="title"
				bind:value={title}
				placeholder="Analysis of Climate Temperature Trends"
				class="input"
			/>
		</div>

		<!-- Description -->
		<div class="card p-6">
			<label for="description" class="block text-sm font-medium text-gray-700 mb-2">
				Description
			</label>
			<textarea
				id="description"
				bind:value={description}
				placeholder="Describe your analysis goals, findings, and conclusions..."
				rows="4"
				class="input"
			/>
		</div>

		<!-- Methodology -->
		<div class="card p-6">
			<label for="methodology" class="block text-sm font-medium text-gray-700 mb-2">
				Methodology
			</label>
			<textarea
				id="methodology"
				bind:value={methodology}
				placeholder="Describe the methods and techniques used in your analysis..."
				rows="4"
				class="input"
			/>
		</div>

		<!-- Data Sources -->
		<div class="card p-6">
			<label class="block text-sm font-medium text-gray-700 mb-2">
				Data Sources
			</label>
			<div class="flex gap-2 mb-4">
				<input
					type="text"
					bind:value={newSource}
					placeholder="Enter DOI, URL, or dataset name"
					class="input flex-1"
					on:keydown={(e) => e.key === 'Enter' && addDataSource()}
				/>
				<button on:click={addDataSource} class="btn btn-primary">
					Add
				</button>
			</div>
			{#if dataSources.length > 0}
				<ul class="space-y-2">
					{#each dataSources as source, index}
						<li class="flex items-center justify-between bg-gray-50 rounded-lg px-3 py-2">
							<span class="text-sm text-gray-700">{source}</span>
							<button
								on:click={() => removeDataSource(index)}
								class="text-gray-400 hover:text-red-500"
							>
								<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
								</svg>
							</button>
						</li>
					{/each}
				</ul>
			{:else}
				<p class="text-sm text-gray-500">No data sources added yet.</p>
			{/if}
		</div>

		<!-- Provenance Info -->
		<div class="card p-6 bg-blue-50 border-blue-200">
			<h3 class="font-semibold text-blue-900 mb-2">Provenance Tracking</h3>
			<p class="text-sm text-blue-700">
				ODDOL automatically tracks data provenance using the PROV-O standard.
				All transformations, queries, and visualizations are recorded for reproducibility.
			</p>
		</div>

		<!-- Export Options -->
		<div class="card p-6">
			<h3 class="font-semibold text-gray-900 mb-4">Export Documentation</h3>
			<div class="flex flex-wrap gap-3">
				<button on:click={() => handleExport('markdown')} class="btn btn-outline">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
					</svg>
					Markdown
				</button>
				<button on:click={() => handleExport('json')} class="btn btn-outline">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4" />
					</svg>
					JSON-LD
				</button>
				<button on:click={() => handleExport('bibtex')} class="btn btn-outline">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
					</svg>
					BibTeX
				</button>
			</div>
		</div>
	</div>
</div>
