<script lang="ts">
	import { onMount } from 'svelte';
	import { browser } from '$app/environment';

	let title = '';
	let description = '';
	let methodology = '';
	let dataSources: string[] = [];
	let newSource = '';
	let generatedBy = 'ODDOL User';
	let usedQuery = '';

	const DESCRIBE_DRAFT_KEY = 'oddol:describe-draft';

	interface DescribeDraft {
		title?: string;
		description?: string;
		methodology?: string;
		dataSources?: string[];
		generatedBy?: string;
		usedQuery?: string;
	}

	onMount(() => {
		if (!browser) return;

		const rawDraft = sessionStorage.getItem(DESCRIBE_DRAFT_KEY);
		if (!rawDraft) return;
		sessionStorage.removeItem(DESCRIBE_DRAFT_KEY);

		try {
			const draft = JSON.parse(rawDraft) as DescribeDraft;

			if (!title && draft.title) title = draft.title;
			if (!description && draft.description) description = draft.description;
			if (!methodology && draft.methodology) methodology = draft.methodology;
			if (!usedQuery && draft.usedQuery) usedQuery = draft.usedQuery;
			if ((!generatedBy || generatedBy === 'ODDOL User') && draft.generatedBy) {
				generatedBy = draft.generatedBy;
			}
			if (Array.isArray(draft.dataSources) && draft.dataSources.length > 0) {
				dataSources = Array.from(new Set([...dataSources, ...draft.dataSources]));
			}
		} catch {
			// Ignore invalid draft payloads.
		}
	});

	function addDataSource() {
		if (newSource.trim() && !dataSources.includes(newSource.trim())) {
			dataSources = [...dataSources, newSource.trim()];
			newSource = '';
		}
	}

	function removeDataSource(index: number) {
		dataSources = dataSources.filter((_, i) => i !== index);
	}

	function handleExport(format: 'markdown' | 'provjsonld' | 'bibtex') {
		let content = '';
		let filename = '';
		let mimeType = '';

		switch (format) {
			case 'markdown':
				content = generateMarkdown();
				filename = 'analysis-description.md';
				mimeType = 'text/markdown';
				break;
			case 'provjsonld':
				content = JSON.stringify(generateProvJsonLd(), null, 2);
				filename = 'analysis-provenance.jsonld';
				mimeType = 'application/json';
				break;
			case 'bibtex':
				content = generateBibtex();
				filename = 'analysis-citation.bib';
				mimeType = 'text/plain';
				break;
		}

		const blob = new Blob([content], { type: mimeType });
		const url = URL.createObjectURL(blob);
		const a = document.createElement('a');
		a.href = url;
		a.download = filename;
		a.click();
		URL.revokeObjectURL(url);
	}

	function generateMarkdown(): string {
		return `# ${title}

## Description

${description}

## Methodology

${methodology}

## Query (Optional)

${usedQuery || 'N/A'}

## Data Sources

${dataSources.map((s) => `- ${s}`).join('\n')}

## Generated By

${generatedBy}

---

*Generated by ODDOL - Open Data Driven Online Learning*
*Date: ${new Date().toLocaleDateString()}*
`;
	}

	function generateProvJsonLd() {
		const now = new Date().toISOString();
		const analysisId = `urn:oddol:analysis:${crypto.randomUUID()}`;
		const activityId = `urn:oddol:activity:${crypto.randomUUID()}`;
		const agentId = `urn:oddol:agent:${slugify(generatedBy || 'oddol-user')}`;

		const sourceEntities = dataSources.map((source, index) => ({
			'@id': `urn:oddol:source:${index + 1}`,
			'@type': 'prov:Entity',
			'rdfs:label': source
		}));

		return {
			'@context': {
				prov: 'http://www.w3.org/ns/prov#',
				dcterms: 'http://purl.org/dc/terms/',
				schema: 'https://schema.org/',
				rdfs: 'http://www.w3.org/2000/01/rdf-schema#'
			},
			'@graph': [
				{
					'@id': analysisId,
					'@type': ['prov:Entity', 'schema:CreativeWork'],
					'dcterms:title': title || 'Untitled analysis',
					'dcterms:description': description || '',
					'schema:abstract': methodology || '',
					'prov:generatedAtTime': now
				},
				{
					'@id': activityId,
					'@type': ['prov:Activity', 'schema:Action'],
					'rdfs:label': 'Manual analysis description',
					'dcterms:description': usedQuery || 'No query documented',
					'prov:endedAtTime': now,
					'prov:wasAssociatedWith': { '@id': agentId },
					'prov:generated': { '@id': analysisId },
					'prov:used': sourceEntities.map((s) => ({ '@id': s['@id'] }))
				},
				{
					'@id': agentId,
					'@type': ['prov:Agent', 'schema:Person'],
					'rdfs:label': generatedBy || 'ODDOL User'
				},
				...sourceEntities
			]
		};
	}

	function slugify(value: string): string {
		return value
			.toLowerCase()
			.trim()
			.replace(/[^a-z0-9]+/g, '-')
			.replace(/^-+|-+$/g, '')
			.slice(0, 64);
	}

	function generateBibtex(): string {
		const key = title.toLowerCase().replace(/\s+/g, '_').slice(0, 20);
		return `@misc{${key},
  title = {${title}},
  note = {${description.slice(0, 200)}...},
  howpublished = {ODDOL - Open Data Driven Online Learning},
  year = {${new Date().getFullYear()}}
}`;
	}
</script>

<svelte:head>
	<title>Describe Analysis - ODDOL</title>
</svelte:head>

<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
	<div class="mb-8">
		<h1 class="text-3xl font-bold text-gray-900 mb-2">Describe Your Analysis</h1>
		<p class="text-gray-600">
			Document your data analysis, methods, and sources. Export in multiple formats.
		</p>
	</div>

	<div class="space-y-6">
		<!-- Title -->
		<div class="card p-6">
			<label for="title" class="block text-sm font-medium text-gray-700 mb-2">
				Title
			</label>
			<input
				type="text"
				id="title"
				bind:value={title}
				placeholder="Analysis of Climate Temperature Trends"
				class="input"
			/>
		</div>

		<!-- Description -->
		<div class="card p-6">
			<label for="description" class="block text-sm font-medium text-gray-700 mb-2">
				Description
			</label>
			<textarea
				id="description"
				bind:value={description}
				placeholder="Describe your analysis goals, findings, and conclusions..."
				rows="4"
				class="input"
			></textarea>
		</div>

		<!-- Methodology -->
		<div class="card p-6">
			<label for="methodology" class="block text-sm font-medium text-gray-700 mb-2">
				Methodology
			</label>
			<textarea
				id="methodology"
				bind:value={methodology}
				placeholder="Describe the methods and techniques used in your analysis..."
				rows="4"
				class="input"
			></textarea>
		</div>

		<!-- Data Sources -->
		<div class="card p-6">
			<label for="data-source-input" class="block text-sm font-medium text-gray-700 mb-2">
				Data Sources
			</label>
			<div class="flex gap-2 mb-4">
				<input
					id="data-source-input"
					type="text"
					bind:value={newSource}
					placeholder="Enter DOI, URL, or dataset name"
					class="input flex-1"
					on:keydown={(e) => e.key === 'Enter' && addDataSource()}
				/>
				<button on:click={addDataSource} class="btn btn-primary">
					Add
				</button>
			</div>
			{#if dataSources.length > 0}
				<ul class="space-y-2">
					{#each dataSources as source, index}
						<li class="flex items-center justify-between bg-gray-50 rounded-lg px-3 py-2">
							<span class="text-sm text-gray-700">{source}</span>
								<button
									on:click={() => removeDataSource(index)}
									aria-label="Remove data source"
									class="text-gray-400 hover:text-red-500"
								>
								<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
								</svg>
							</button>
						</li>
					{/each}
				</ul>
			{:else}
				<p class="text-sm text-gray-500">No data sources added yet.</p>
			{/if}
		</div>

		<!-- Provenance Metadata -->
		<div class="card p-6">
			<h3 class="font-semibold text-gray-900 mb-4">Provenance Metadata (Manual)</h3>
			<div class="space-y-4">
				<div>
					<label for="generated-by" class="block text-sm font-medium text-gray-700 mb-2">
						Generated By
					</label>
					<input
						id="generated-by"
						type="text"
						bind:value={generatedBy}
						placeholder="Your name or team"
						class="input"
					/>
				</div>
				<div>
					<label for="used-query" class="block text-sm font-medium text-gray-700 mb-2">
						Query / Workflow Notes (Optional)
					</label>
					<input
						id="used-query"
						type="text"
						bind:value={usedQuery}
						placeholder="e.g., SELECT * FROM climate_data WHERE year >= 2020"
						class="input"
					/>
				</div>
			</div>
		</div>

		<!-- Provenance Info -->
		<div class="card p-6 bg-blue-50 border-blue-200">
			<h3 class="font-semibold text-blue-900 mb-2">Provenance Notes</h3>
			<p class="text-sm text-blue-700">
				ODDOL supports manual PROV-O compatible export from these fields.
				Automatic provenance tracking is not implemented.
			</p>
		</div>

		<!-- Export Options -->
		<div class="card p-6">
			<h3 class="font-semibold text-gray-900 mb-4">Export Documentation</h3>
			<div class="flex flex-wrap gap-3">
				<button on:click={() => handleExport('markdown')} class="btn btn-outline">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
					</svg>
					Markdown
				</button>
				<button on:click={() => handleExport('provjsonld')} class="btn btn-outline">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4" />
					</svg>
					PROV JSON-LD
				</button>
				<button on:click={() => handleExport('bibtex')} class="btn btn-outline">
					<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
					</svg>
					BibTeX
				</button>
			</div>
		</div>
	</div>
</div>
